org: ghostlambda
app: generador-diagramas
service: diagrams-lambda

provider:
  name: aws
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::137805459264:role/ServerlessDeploymentRole

  ecr:
    images:
      graphviz:
        path: .  # Ruta donde está tu Dockerfile

functions:
  api:
    image:
      name: graphviz
    events:
      - http:
          path: diagram
          method: post
