org: sefedeam
service: diagrams-lambda

provider:
  name: aws
  # Ya que usas contenedor, el runtime lo ignora
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::195602400559:role/LabRole

functions:
  api:
    image:
      uri: 195602400559.dkr.ecr.us-east-1.amazonaws.com/sefedeam/gosip:latest
    events:
      - http:
          path: diagram
          method: post
